import { useEffect, useState } from 'react';
import { LoadingIndicator } from './LoadingIndicator';
import { Modal } from './Modal';
import './ApprovalRevisionRegenerateModal.css';

type Result = { fileName: string; objectUrl: string };
type Props = { graphicId:number; revisionId:number|null; revisionLabel:string; isOpen:boolean; onClose:()=>void };

export function PrintCardRevisionRegenerateModal({graphicId,revisionId,revisionLabel,isOpen,onClose}:Props){
  const [result,setResult]=useState<Result|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  useEffect(()=>{ if(!isOpen||!revisionId)return; let cancelled=false; let objectUrl=''; setLoading(true);setError(null);setResult(null); void fetch(`/api/graphics/${graphicId}/print-card/revisions/${revisionId}.jpg`).then(async response=>{if(!response.ok){const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error||'The Print Card could not be regenerated.');}const disposition=response.headers.get('Content-Disposition')??'';const matched=disposition.match(/filename="?([^";]+)"?/i);const fileName=matched?.[1]||`PRINT_CARD_REV_${revisionLabel}.jpg`;const blob=await response.blob();objectUrl=URL.createObjectURL(blob);return{fileName,objectUrl};}).then(body=>{if(!cancelled)setResult(body);}).catch((reason:unknown)=>{if(!cancelled)setError(reason instanceof Error?reason.message:'The Print Card could not be regenerated.');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;if(objectUrl)URL.revokeObjectURL(objectUrl);}; },[graphicId,revisionId,revisionLabel,isOpen]);
  const print=()=>{if(!result)return;const windowRef=window.open(result.objectUrl,'_blank','noopener,noreferrer');if(!windowRef)setError('Allow pop-ups to open the printable Print Card image.');};
  const download=()=>{if(!result)return;const link=document.createElement('a');link.href=result.objectUrl;link.download=result.fileName;document.body.appendChild(link);link.click();link.remove();};
  return <Modal isOpen={isOpen} onClose={loading?()=>undefined:onClose} title={`Regenerate Print Card · Revision ${revisionLabel}`}><div className="approval-regenerate-result">{loading&&<LoadingIndicator title="Regenerating Print Card" message="Building a fresh temporary JPG from the saved revision information and connected artwork…" size="panel"/>}{!loading&&error&&<div className="approval-regenerate-error"><strong>Print Card could not be regenerated</strong><span>{error}</span></div>}{!loading&&result&&<><div className="approval-regenerate-success"><span>✓</span><div><p className="eyebrow">Temporary JPG ready</p><h3>{result.fileName}</h3><p>This Print Card was rebuilt from the selected V3 revision. It is temporary and does not replace the managed or live Print Card image.</p></div></div><div className="approval-regenerate-actions"><button onClick={print} type="button"><strong>Print</strong><span>Open the finished Print Card in a new window</span></button><button className="primary" onClick={download} type="button"><strong>Download JPG</strong><span>Save a copy to your computer</span></button></div><footer><button onClick={onClose} type="button">Done</button></footer></>}{!loading&&error&&<footer><button onClick={onClose} type="button">Close</button></footer>}</div></Modal>;
}
