import Fastify from 'fastify';
import {
  approvalRevisionDetailResponseSchema, approvalRevisionUpdateSchema,
  companySettingsInputSchema, companySettingsSchema, createGraphicInputSchema, createGraphicResponseSchema,
  createPrintCardResponseSchema, deleteGraphicResponseSchema, fileIndexJobStatusSchema, graphicFilesResponseSchema,
  graphicsListResponseSchema, graphicsQuerySchema, healthResponseSchema, onboardPrintCardInputSchema,
  onboardPrintCardResponseSchema, pathValidationResponseSchema, previewResponseSchema, previewVariantSchema,
  printCardArtworkMatchesResponseSchema, printCardDefaultsResponseSchema, printCardDetailsResponseSchema,
  printCardDraftSchema, revisionLookupQuerySchema, revisionLookupResponseSchema, storageSettingsSchema,
} from '@graphicsflow/shared';
import { renderHccApprovalPreview, type ApprovalPreviewInput } from './approval-creator-preview-service.js';
import { readManagedApprovalRevision, saveManagedApproval } from './approval-managed-production-service.js';
import { resolveApprovalDocument, streamApprovalDocument } from './approval-document-service.js';
import { getApprovalRevisionDetail, updateApprovalRevision } from './approval-revision-service.js';
import { config } from './config.js';
import { resolvedDatabasePath } from './database.js';
import { createGraphic, deleteGraphic, DuplicateGraphicError, getGraphicById, GraphicDeletionError, listGraphics } from './graphics-repository.js';
import { getFileIndexJobStatus, resolveGraphicFiles, startLiveFileIndexJob } from './live-file-service.js';
import { getLiveFileSyncStatus, initializeLiveFileSync, restartLiveFileSync, scheduleGraphicFileMissRepair } from './live-file-sync-service.js';
import { getOrGeneratePreview, readPreviewImage } from './preview-service.js';
import { findPrintCardArtworkMatches, readLiveArtwork } from './print-card-artwork-service.js';
import { readCurrentPrintCard, readUnregisteredPrintCard } from './print-card-document-service.js';
import { createManagedPrintCard, getCurrentPrintCardDetails } from './print-card-managed-production-service.js';
import { onboardPrintCard } from './print-card-onboarding-service.js';
import { getApprovalHeaderMetadata, getApprovalRevisionAutofill, renderArtworkPreview, renderCompletePrintCardPreview } from './print-card-preview-service.js';
import { registerPrintCardRevisionRoutes } from './print-card-revision-routes.js';
import { getPrintCardDefaults } from './print-card-service.js';
import { lookupRevisionWorkspace } from './revision-workspace-service.js';
import { getCompanySettings, saveCompanySettings, settingsDatabasePath, validateStoragePaths } from './settings-store.js';

const app = Fastify({ logger: true, bodyLimit: 45 * 1024 * 1024 });
const badId = (value: unknown) => { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : null; };
const approvalInput = (graphic: NonNullable<ReturnType<typeof getGraphicById>>, body: Record<string, unknown>): ApprovalPreviewInput => ({
  gNumber: graphic.gNumber,
  customerNumber: graphic.customerNumber,
  customerName: graphic.customerName,
  partNumber: graphic.partNumber,
  specificationNumber: String(body.specificationNumber ?? ''),
  designNumber: String(body.designNumber ?? ''),
  fluteTest: String(body.fluteTest ?? ''),
  salesRep: String(body.salesRep ?? ''),
  revisionLabel: String(body.revisionLabel ?? '0'),
  revisionDate: String(body.revisionDate ?? ''),
  description: String(body.description ?? 'FOR APPROVAL'),
  csr: String(body.csr ?? ''),
  designer: String(body.designer ?? ''),
  digitalPrint: body.digitalPrint === true,
  digitalCut: body.digitalCut === true,
  digitalDieCut: body.digitalDieCut === true,
  labelDieCut: body.labelDieCut === true,
  label4cProcess: body.label4cProcess === true,
  artPdfName: String(body.artPdfName ?? ''),
  artPdfBase64: String(body.artPdfBase64 ?? ''),
  liveArtworkRelativePath: String(body.liveArtworkRelativePath ?? ''),
});

app.get('/api/health', async () => healthResponseSchema.parse({ status: 'ok', service: 'graphicsflow-api', version: '0.1.0', timestamp: new Date().toISOString() }));
app.get('/api/graphics', async (request, reply) => { const parsed = graphicsQuerySchema.safeParse(request.query); if (!parsed.success) return reply.status(400).send({ error: 'Invalid graphics query.', details: parsed.error.flatten() }); try { return graphicsListResponseSchema.parse(listGraphics(parsed.data)); } catch (error) { request.log.error({ error, databasePath: resolvedDatabasePath }, 'Could not load graphics records'); return reply.status(500).send({ error: 'Graphics records could not be loaded.' }); } });
app.post('/api/graphics', async (request, reply) => { const parsed = createGraphicInputSchema.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: 'The graphics record is invalid.', details: parsed.error.flatten() }); try { return reply.status(201).send(createGraphicResponseSchema.parse({ graphic: createGraphic(parsed.data) })); } catch (error) { if (error instanceof DuplicateGraphicError) return reply.status(409).send({ error: error.message }); request.log.error({ error }, 'Could not create graphics record'); return reply.status(500).send({ error: 'The G# could not be created.' }); } });
app.delete('/api/graphics/:id', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); try { return deleteGraphicResponseSchema.parse(deleteGraphic(id)); } catch (error) { if (error instanceof GraphicDeletionError) return reply.status(error.code === 'not-found' ? 404 : 409).send({ error: error.message, code: error.code }); request.log.error({ error, graphicId: id }, 'Could not delete graphics record'); return reply.status(500).send({ error: 'The graphics record could not be deleted.' }); } });
app.get('/api/graphics/:id/files', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const graphic = getGraphicById(id); if (!graphic) return reply.status(404).send({ error: 'Graphics record not found.' }); try { const files = await resolveGraphicFiles(graphic.gNumber); const missing: Array<'approval' | 'printCard'> = []; if (!files.approval.latest) missing.push('approval'); if (!files.printCard.latest) missing.push('printCard'); scheduleGraphicFileMissRepair(graphic.gNumber, missing); return graphicFilesResponseSchema.parse(files); } catch (error) { request.log.error({ error, graphicId: id }, 'Could not resolve live graphic files'); return reply.status(500).send({ error: 'Live files could not be resolved.' }); } });
app.get('/api/revisions/lookup', async (request, reply) => { const parsed = revisionLookupQuerySchema.safeParse(request.query); if (!parsed.success) return reply.status(400).send({ error: 'Choose Approval or Print Card and enter a valid identifier.', details: parsed.error.flatten() }); try { return revisionLookupResponseSchema.parse(await lookupRevisionWorkspace(parsed.data)); } catch (error) { request.log.error({ error, query: parsed.data }, 'Could not look up revision history'); return reply.status(500).send({ error: 'Revision history could not be searched.' }); } });
app.get('/api/graphics/:id/approval/revisions/:revisionId', async (request, reply) => { const params = request.params as { id?: string; revisionId?: string }; const id = badId(params.id); const revisionId = badId(params.revisionId); if (!id || !revisionId) return reply.status(400).send({ error: 'Invalid Approval revision request.' }); const revision = getApprovalRevisionDetail(id, revisionId); return revision ? approvalRevisionDetailResponseSchema.parse({ revision }) : reply.status(404).send({ error: 'Approval revision not found.' }); });
app.patch('/api/graphics/:id/approval/revisions/:revisionId', async (request, reply) => { const params = request.params as { id?: string; revisionId?: string }; const id = badId(params.id); const revisionId = badId(params.revisionId); if (!id || !revisionId) return reply.status(400).send({ error: 'Invalid Approval revision request.' }); const parsed = approvalRevisionUpdateSchema.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: 'The Approval revision information is invalid.', details: parsed.error.flatten() }); try { return approvalRevisionDetailResponseSchema.parse({ revision: updateApprovalRevision(id, revisionId, parsed.data) }); } catch (error) { const message = error instanceof Error ? error.message : 'The Approval revision could not be updated.'; request.log.error({ error, graphicId: id, revisionId }, 'Could not update Approval revision'); return reply.status(/already exists|not found/i.test(message) ? 409 : 500).send({ error: message }); } });
app.get('/api/revisions/unregistered-print-card', async (request, reply) => { const relativePath = String((request.query as { relativePath?: unknown }).relativePath ?? '').trim(); if (!relativePath) return reply.status(400).send({ error: 'A live Print Card path is required.' }); const image = await readUnregisteredPrintCard(relativePath); return image ? reply.header('Content-Type', image.contentType).header('Cache-Control', 'private, no-cache').send(image.data) : reply.status(404).send({ error: 'The live Print Card could not be opened.' }); });
app.post('/api/revisions/onboard-print-card', async (request, reply) => { const parsed = onboardPrintCardInputSchema.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: 'Complete the record information and add at least one revision.', details: parsed.error.flatten() }); try { return reply.status(201).send(onboardPrintCardResponseSchema.parse({ record: onboardPrintCard(parsed.data) })); } catch (error) { const message = error instanceof Error ? error.message : 'The Print Card record could not be created.'; request.log.error({ error }, 'Could not onboard live Print Card'); return reply.status(409).send({ error: message }); } });

app.post('/api/graphics/:id/approval/preview', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const graphic = getGraphicById(id); if (!graphic) return reply.status(404).send({ error: 'Graphics record not found.' }); try { return reply.header('Content-Type', 'image/png').header('Cache-Control', 'private, no-store').send(await renderHccApprovalPreview(approvalInput(graphic, (request.body ?? {}) as Record<string, unknown>))); } catch (error) { const message = error instanceof Error ? error.message : 'The Approval preview could not be rendered.'; request.log.error({ error, graphicId: id }, 'Could not render HCC Approval preview'); return reply.status(422).send({ error: message }); } });
app.post('/api/graphics/:id/approval', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const graphic = getGraphicById(id); if (!graphic) return reply.status(404).send({ error: 'Graphics record not found.' }); try { return reply.status(201).send(await saveManagedApproval(id, approvalInput(graphic, (request.body ?? {}) as Record<string, unknown>))); } catch (error) { const message = error instanceof Error ? error.message : 'The Approval could not be saved.'; request.log.error({ error, graphicId: id }, 'Could not save managed Approval'); return reply.status(/already exists|required|invalid|cannot/i.test(message) ? 409 : 500).send({ error: message }); } });
app.get('/api/graphics/:id/approval/revisions/:revisionId.pdf', async (request, reply) => { const id = badId((request.params as { id?: string }).id); const revisionId = badId((request.params as { revisionId?: string }).revisionId); if (!id || !revisionId) return reply.status(400).send({ error: 'Invalid Approval revision request.' }); const download = (request.query as { download?: string } | undefined)?.download === '1'; const document = await readManagedApprovalRevision(id, revisionId, download); if (!document) return reply.status(404).send({ error: 'The temporary Approval PDF is no longer available. Regenerate it from the saved revision.' }); return reply.header('Content-Type', 'application/pdf').header('Content-Disposition', `${download ? 'attachment' : 'inline'}; filename="${document.fileName.replace(/"/g, '')}"`).header('Cache-Control', 'private, no-store').send(document.data); });
app.get('/api/graphics/:id/approval/metadata', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); if (!getGraphicById(id)) return reply.status(404).send({ error: 'Graphics record not found.' }); try { return await getApprovalHeaderMetadata(id); } catch (error) { request.log.error({ error, graphicId: id }, 'Could not read Approval header metadata'); return reply.status(500).send({ error: 'Approval header information could not be read.' }); } });
app.get('/api/graphics/:id/print-card/defaults', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); try { const defaults = await getPrintCardDefaults(id); if (!defaults) return reply.status(404).send({ error: 'Graphics record not found.' }); const approval = await getApprovalRevisionAutofill(id); if (approval) { if (!defaults.draft.csr && approval.csr) { defaults.draft.csr = approval.csr; defaults.autoFill.sources.csr = 'Approval revision table'; } if (!defaults.draft.designer && approval.designer) { defaults.draft.designer = approval.designer; defaults.autoFill.sources.designer = 'Approval revision table'; } if (!defaults.draft.description && approval.description) { defaults.draft.description = approval.description; defaults.autoFill.sources.description = 'Approval revision table'; } } return printCardDefaultsResponseSchema.parse(defaults); } catch (error) { request.log.error({ error, graphicId: id }, 'Could not load print card defaults'); return reply.status(500).send({ error: 'Print Card defaults could not be loaded.' }); } });
app.get('/api/graphics/:id/print-card/artwork-matches', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); try { const matches = await findPrintCardArtworkMatches(id); if (!matches) return reply.status(404).send({ error: 'Graphics record not found.' }); return printCardArtworkMatchesResponseSchema.parse(matches); } catch (error) { request.log.error({ error, graphicId: id }, 'Could not find live artwork PDFs'); return reply.status(500).send({ error: 'Live artwork PDFs could not be checked.' }); } });
app.post('/api/print-card/artwork-preview', async (request, reply) => { const body = request.body as { artPdfBase64?: unknown; graphicId?: unknown; liveArtworkRelativePath?: unknown } | null; try { let base64 = typeof body?.artPdfBase64 === 'string' ? body.artPdfBase64.trim() : ''; if (!base64 && Number.isInteger(Number(body?.graphicId)) && typeof body?.liveArtworkRelativePath === 'string') base64 = (await readLiveArtwork(body.liveArtworkRelativePath)).data.toString('base64'); if (!base64) return reply.status(400).send({ error: 'Select a live artwork PDF or upload a PDF first.' }); return reply.header('Content-Type', 'image/png').header('Cache-Control', 'no-store').send(await renderArtworkPreview(base64)); } catch (error) { const message = error instanceof Error ? error.message : 'The artwork preview could not be generated.'; request.log.error({ error }, 'Could not generate artwork preview'); return reply.status(422).send({ error: message }); } });
app.post('/api/graphics/:id/print-card/preview', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const body = (request.body ?? {}) as Record<string, unknown>; const draft = { specificationNumber: String(body.specificationNumber ?? '').trim(), designNumber: String(body.designNumber ?? '').trim(), revisionLabel: String(body.revisionLabel ?? '').trim(), revisionDate: String(body.revisionDate ?? '').trim(), description: String(body.description ?? '').trim(), csr: String(body.csr ?? '').trim(), designer: String(body.designer ?? '').trim(), replaceExistingImage: body.replaceExistingImage === true, artPdfName: String(body.artPdfName ?? '').trim(), artPdfBase64: String(body.artPdfBase64 ?? ''), liveArtworkRelativePath: String(body.liveArtworkRelativePath ?? '').trim() }; if (!draft.artPdfBase64 && !draft.liveArtworkRelativePath) return reply.status(400).send({ error: 'Select a live artwork PDF or upload a PDF before opening the Print Card Preview.' }); try { return reply.header('Content-Type', 'image/png').header('Cache-Control', 'private, no-store').send(await renderCompletePrintCardPreview(id, draft)); } catch (error) { const message = error instanceof Error ? error.message : 'The Print Card preview could not be rendered.'; request.log.error({ error }, 'Could not render complete Print Card preview'); return reply.status(422).send({ error: message }); } });
app.post('/api/graphics/:id/print-card', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const parsed = printCardDraftSchema.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: 'The Print Card information is invalid.', details: parsed.error.flatten() }); try { return reply.status(201).send(createPrintCardResponseSchema.parse(await createManagedPrintCard(id, parsed.data))); } catch (error) { const message = error instanceof Error ? error.message : 'The Print Card could not be created.'; request.log.error({ error, graphicId: id }, 'Could not create print card'); return reply.status(/already exists|configure|required|invalid|select|upload|artwork/i.test(message) ? 409 : 500).send({ error: message }); } });
app.get('/api/graphics/:id/print-card/details', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const details = getCurrentPrintCardDetails(id); return details ? printCardDetailsResponseSchema.parse(details) : reply.status(404).send({ error: 'Graphics record not found.' }); });
app.get('/api/graphics/:id/print-card.jpg', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); const query = request.query as { download?: string; specificationNumber?: string } | undefined; const image = await readCurrentPrintCard(id, query?.specificationNumber ?? ''); if (!image) return reply.status(404).send({ error: 'No generated or live Print Card image is available.' }); const download = query?.download === '1'; return reply.header('Content-Type', image.contentType).header('Content-Disposition', `${download ? 'attachment' : 'inline'}; filename="${image.fileName.replace(/"/g, '')}"`).header('Cache-Control', image.source === 'live' ? 'private, no-cache' : 'private, no-store').header('X-GraphicsFlow-Document-Source', image.source).send(image.data); });
app.get('/api/graphics/:id/approval.pdf', async (request, reply) => { const id = badId((request.params as { id?: string }).id); if (!id) return reply.status(400).send({ error: 'Invalid graphics record id.' }); if (!getGraphicById(id)) return reply.status(404).send({ error: 'Graphics record not found.' }); const download = (request.query as { download?: string } | undefined)?.download === '1'; try { const document = await resolveApprovalDocument(id); if (!document) return reply.status(404).send({ error: 'Approval PDF is not available.' }); return reply.header('Content-Type', 'application/pdf').header('Content-Disposition', `${download ? 'attachment' : 'inline'}; filename="${document.fileName.replace(/"/g, '')}"`).header('Cache-Control', 'private, no-store').send(await streamApprovalDocument(document)); } catch (error) { request.log.error({ error, graphicId: id }, 'Could not stream approval PDF'); return reply.status(500).send({ error: 'The approval PDF could not be opened.' }); } });
app.get('/api/previews/:graphicId/:variant', async (request, reply) => { const params = request.params as { graphicId?: string; variant?: string }; const id = badId(params.graphicId); const variant = previewVariantSchema.safeParse(params.variant); if (!id || !variant.success) return reply.status(400).send({ error: 'Invalid preview request.' }); if (!getGraphicById(id)) return reply.status(404).send({ error: 'Graphics record not found.' }); try { return previewResponseSchema.parse(await getOrGeneratePreview(id, variant.data)); } catch (error) { request.log.error({ error, graphicId: id }, 'Could not generate preview'); return reply.status(500).send({ error: 'Preview could not be generated.' }); } });
app.get('/api/previews/:graphicId/:variant/image', async (request, reply) => { const params = request.params as { graphicId?: string; variant?: string }; const id = badId(params.graphicId); const variant = previewVariantSchema.safeParse(params.variant); if (!id || !variant.success) return reply.status(400).send({ error: 'Invalid preview request.' }); const image = await readPreviewImage(id, variant.data); return image ? reply.header('Content-Type', 'image/png').header('Cache-Control', 'private, max-age=3600').send(image) : reply.status(404).send({ error: 'Preview image is not available.' }); });
app.get('/api/settings/company', async () => companySettingsSchema.parse(getCompanySettings()));
app.put('/api/settings/company', async (request, reply) => { const parsed = companySettingsInputSchema.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: 'Company settings are invalid.', details: parsed.error.flatten() }); try { const saved = companySettingsSchema.parse(saveCompanySettings(parsed.data)); restartLiveFileSync(); return saved; } catch (error) { request.log.error({ error }, 'Could not save company settings'); return reply.status(500).send({ error: 'Company settings could not be saved.' }); } });
app.post('/api/settings/validate-paths', async (request, reply) => { const parsed = storageSettingsSchema.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: 'Storage paths are invalid.', details: parsed.error.flatten() }); try { return pathValidationResponseSchema.parse(await validateStoragePaths(parsed.data)); } catch (error) { request.log.error({ error }, 'Could not validate storage paths'); return reply.status(500).send({ error: 'Storage paths could not be checked.' }); } });
app.post('/api/file-index/refresh', async () => startLiveFileIndexJob());
app.get('/api/file-index/status', async () => fileIndexJobStatusSchema.parse(getFileIndexJobStatus()));
app.get('/api/live-file-sync/status', async () => getLiveFileSyncStatus());
registerPrintCardRevisionRoutes(app);

await app.listen({ host: '127.0.0.1', port: config.SERVER_PORT });
initializeLiveFileSync();
app.log.info({ host: '127.0.0.1', port: config.SERVER_PORT, databasePath: resolvedDatabasePath, settingsDatabasePath }, 'GraphicsFlow server started');